FROM alpine:3.8 as scripts

MAINTAINER andrey.dyachkov@gmail.com

RUN mkdir nakadi
WORKDIR /nakadi
RUN apk add --no-cache curl wget jq tar git
RUN git clone https://github.com/zalando/nakadi.git .

FROM arm64v8/postgres
COPY --from=scripts /nakadi/database/nakadi /docker-entrypoint-initdb.d

