name: Build and push Nakadi version

on:
  push:
    branches:
      - 'pr**'
  pull_request:
    branches:
      - master 
      - main

env:
  NAKADI_VERSION: 3.5
  PG_IMAGE_NAME: postgres
  NAKADI_IMAGE_NAME: nakadi

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Build and push Nakadi image
        run: | 
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          IMAGE_ID=ghcr.io/${{ github.repository }}/$NAKADI_IMAGE_NAME

          docker buildx create --use
          docker buildx build --file Dockerfile --platform linux/amd64,linux/arm64 --tag $IMAGE_ID:$NAKADI_VERSION --push .

      - name: Build and push Postgres image
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository }}/$PG_IMAGE_NAME

          docker buildx create --use
          docker buildx build --file Dockerfile-postgres --platform linux/amd64,linux/arm64 --tag $IMAGE_ID:$NAKADI_VERSION --push .

      - name: Check Nakadi lists event types
        run: |
          docker-compose -f docker-compose.yml up -d
          sleep 30
          curl --fail http://localhost:8080/event-types/nakadi.access.log
