name: Docker

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master

env:
  # TODO: Change variable to your image's name.
  PG_VERSION: 13.6
  PG_IMAGE_NAME: postgres
  NAKADI_IMAGE_NAME: nakadi

jobs:
  # Push image to GitHub Packages.
  # See also https://docs.docker.com/docker-hub/builds/
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build nakadi image
        run: docker buildx build --platform linux/arm64 --file ./arm64/Dockerfile --tag image .

      - name: Push nakadi image
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          IMAGE_ID=ghcr.io/${{ github.repository }}/$NAKADI_IMAGE_NAME-arm64
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=latest
          docker tag image $IMAGE_ID:latest
          docker push $IMAGE_ID:latest

      - name: Build postgres image
        run: docker buildx build --platform linux/arm64 --file ./arm64/Dockerfile-postgres --tag image .

      - name: Push postgres image
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          IMAGE_ID=ghcr.io/${{ github.repository }}/$PG_IMAGE_NAME-arm64
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$PG_VERSION
          docker tag image $IMAGE_ID:$PG_VERSION
          docker push $IMAGE_ID:$PG_VERSION
