name: Docker

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master

env:
  # TODO: Change variable to your image's name.
  PG_VERSION: 14.5
  PG_IMAGE_NAME: postgres
  NAKADI_VERSION: 3.5
  NAKADI_IMAGE_NAME: nakadi

jobs:
  # Push image to GitHub Packages.
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Build nakadi image
        run: | 
          docker buildx create
          docker buildx build --file Dockerfile --platform linux/amd64,linux/arm64 --tag image .

      - name: Push versioned nakadi image
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          IMAGE_ID=ghcr.io/${{ github.repository }}/$NAKADI_IMAGE_NAME
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$NAKADI_VERSION

          docker tag image $IMAGE_ID:$NAKADI_VERSION
          docker push $IMAGE_ID:$NAKADI_VERSION

      - name: Build postgres image
        run: |
          docker buildx create
          docker buildx build --file Dockerfile-postgres --platform linux/amd64,linux/arm64 --tag image .

      - name: Push postgres image
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          IMAGE_ID=ghcr.io/${{ github.repository }}/$PG_IMAGE_NAME
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$PG_VERSION

          docker tag image $IMAGE_ID:$PG_VERSION
          docker push $IMAGE_ID:$PG_VERSION

      - name: Check Nakadi lists event types
        run: |
          docker-compose -f docker-compose-github.yml up -d
          sleep 30
          curl --fail http://localhost:8080/event-types/nakadi.access.log
